name: Validate Data Contract

on:
  push:
    paths:
      - 'data/**/*.csv'
      - 'contracts/**/*.yaml'
  pull_request:
    paths:
      - 'data/**/*.csv'
      - 'contracts/**/*.yaml'
  workflow_dispatch:

jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Hello from the workflow!"
